"""The users table — the primary account record.

The phone number IS the identity. On login we find-or-create ONE row per phone
(the unique key), giving every account a stable UUID primary key (`users.id`)
that ties the person's phone + display name together. The X-Owner-Id used to
scope tasks/prefs stays the phone string (that's what `claim` re-keys onto), so
this table is the canonical identity record without forcing a data re-key.

Idempotent: the same phone always resolves to the same row (upsert on the unique
`phone`), so repeat logins just refresh the name + last_login_at.
"""
from datetime import datetime, timezone
from typing import Any, Optional

from app.core.supabase import get_supabase

_USERS = "users"


def upsert_user(phone: str, *, name: Optional[str] = None) -> dict[str, Any]:
    """Find-or-create the account row for [phone], returning it (with its PK).

    - Creates the row on first sight (UUID `id` generated by the DB).
    - On repeat logins, refreshes `display_name` (when a non-empty name is given)
      and `last_login_at`. A blank/None name never clobbers an existing one.
    """
    now = datetime.now(timezone.utc).isoformat()
    row: dict[str, Any] = {"phone": phone, "last_login_at": now}
    trimmed = (name or "").strip()
    if trimmed:
        row["display_name"] = trimmed

    res = (
        get_supabase()
        .table(_USERS)
        .upsert(row, on_conflict="phone")
        .execute()
    )
    return res.data[0] if res.data else row


def get_user(phone: str) -> Optional[dict[str, Any]]:
    """The account row for [phone], or None if this number has never logged in."""
    res = (
        get_supabase()
        .table(_USERS)
        .select("*")
        .eq("phone", phone)
        .limit(1)
        .execute()
    )
    return res.data[0] if res.data else None
