-- ─────────────────────────────────────────────────────────────────────────────
-- Daily AI one-liners for the Home "today" feed.
--
-- The Home screen conjures each reminder as one catchy, tailor-made sentence.
-- Those sentences are generated by an LLM (Groq) ONCE PER DAY per user and
-- cached here, so the app can render them instantly without re-calling the
-- model on every open. The first request of the day generates + caches; every
-- later read that day just returns the cached rows.
--
-- The Groq API key is an APP-WIDE backend env var (GROQ_API_KEY), never stored
-- per-user in the DB. If it's unset the app falls back to a locally-built
-- sentence and this table stays empty.
-- ─────────────────────────────────────────────────────────────────────────────

-- One cached sentence per (user, task, day). Regenerated daily.
create table if not exists public.daily_task_lines (
    id          uuid primary key default gen_random_uuid(),
    user_id     uuid not null references public.users (id) on delete cascade,
    task_id     uuid not null references public.tasks (id) on delete cascade,
    -- The calendar day (UTC) these lines were generated for. A new day → a new
    -- generation pass.
    for_date    date not null,
    line        text not null,
    created_at  timestamptz not null default now(),

    unique (task_id, for_date)
);

-- Fast "give me this user's lines for today" lookup.
create index if not exists daily_lines_user_date_idx
    on public.daily_task_lines (user_id, for_date);

-- Housekeeping: yesterday's lines are dead weight. A cheap way to keep the
-- table small is to delete anything older than a couple of days on write; the
-- service does this opportunistically, but this index makes the sweep cheap.
create index if not exists daily_lines_date_idx
    on public.daily_task_lines (for_date);

alter table public.daily_task_lines enable row level security;
