// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvev6BVtPEqM_DtYFW4Pjb8p6wl_hkdfY',
    appId: '1:795412577532:web:c0811e4c88572e8427ab79',
    messagingSenderId: '795412577532',
    projectId: 'revolution-86562',
    authDomain: 'revolution-86562.firebaseapp.com',
    storageBucket: 'revolution-86562.firebasestorage.app',
    measurementId: 'G-NC0972MGYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZT41wbZUmM776xA5zoiMqnFstlp6fzkI',
    appId: '1:795412577532:android:5a00769cd59b93b127ab79',
    messagingSenderId: '795412577532',
    projectId: 'revolution-86562',
    storageBucket: 'revolution-86562.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcND95IDaMr813TURrW6SgN-OMscSdys4',
    appId: '1:795412577532:ios:8427f1fa5a9663aa27ab79',
    messagingSenderId: '795412577532',
    projectId: 'revolution-86562',
    storageBucket: 'revolution-86562.firebasestorage.app',
    iosBundleId: 'com.revolution.revolution.dev',
  );
}
